"""
config.py — Centralized configuration for the Polymarket data pipeline.
All thresholds and file paths are defined here; never hard-coded elsewhere.
"""

import os
from pathlib import Path

# ── Paths ─────────────────────────────────────────────────────────────────────
ROOT          = Path(__file__).resolve().parent.parent
DATA_DIR      = ROOT / "data"
RAW_DIR       = DATA_DIR / "raw"
PROCESSED_DIR = DATA_DIR / "processed"
FEATURES_DIR  = DATA_DIR / "features"

# Parquet cache files (auto-generated by db_loader from raw SQLite)
PARQUET_MARKET = PROCESSED_DIR / "market.parquet"
PARQUET_TOKEN  = PROCESSED_DIR / "token_outcome.parquet"
PARQUET_BARS   = PROCESSED_DIR / "trade_price_1m.parquet"
PARQUET_MTAG   = PROCESSED_DIR / "market_tag.parquet"
PARQUET_FTAG   = PROCESSED_DIR / "selected_filter_tag.parquet"

# Source SQLite (not in repo — see data/README.md)
DB_PATH = RAW_DIR / "polymarket_train_2025.sqlite3"


# ── LLM API (pipeline step 5 — semantic market filtering) ────────────────────
# Set via environment variable. Never hard-code API keys in source.
#
#   export LLM_API_KEY="your-key-here"
#   export LLM_BASE_URL="https://api.deepseek.com"   # or openai-compatible endpoint
#   export LLM_MODEL="deepseek-chat"
#
LLM_API_KEY  = os.environ.get("LLM_API_KEY", "")
LLM_BASE_URL = os.environ.get("LLM_BASE_URL", "https://api.deepseek.com")
LLM_MODEL    = os.environ.get("LLM_MODEL", "deepseek-chat")


# ── Usability funnel thresholds ───────────────────────────────────────────────

class FunnelConfig:
    # Filter 1 — Resolution: last YES-token close must be outside this band
    RESOLUTION_YES_THRESHOLD: float = 0.95   # close >= this → YES resolved
    RESOLUTION_NO_THRESHOLD:  float = 0.05   # close <= this → NO  resolved

    # Filter 2 — Temporal validity
    MIN_DURATION_HOURS: float = 1.0          # market must last at least 1 h
    MAX_DURATION_DAYS:  float = 730.0        # sanity upper bound (2 years)

    # Filter 3 — Bet type: only standard binary outcomes
    ACCEPTED_OUTCOME_PAIRS: tuple = (("yes", "no"), ("up", "down"))

    # Filter 4 — Volume / liquidity
    MIN_VOLUME_USDC: float = 1_000.0

    # Filter 5 — Minimum activity
    MIN_TRADES: int = 300

    # Filter 6 — Price continuity
    MAX_GAP_HOURS:  float = 24.0
    MIN_ACTIVE_BARS: int  = 10

    # LLM credentials (pulled from module-level env vars)
    LLM_API_KEY:  str = LLM_API_KEY
    LLM_BASE_URL: str = LLM_BASE_URL
    LLM_MODEL:    str = LLM_MODEL


# ── Logging ───────────────────────────────────────────────────────────────────
LOG_LEVEL       = "INFO"
LOG_FORMAT      = "%(asctime)s | %(levelname)-8s | %(name)s | %(message)s"
LOG_DATE_FORMAT = "%Y-%m-%d %H:%M:%S"
